---
name: service-fabric

instance_groups:
- name: service-fabric
  azs: [z1,z2,z3]
  instances: 5
  vm_type: service-fabric
  stemcell: default
  networks: [{name: service-fabric}]
  env:
    bosh:
      ipv6: {enable: true}
      swap_size: 0
  jobs:
  - name: service-fabric
    release: service-fabric
    properties: {}
  - name: repair
    release: service-fabric
    properties: {}

- name: smoke-test
  azs: [z1]
  instances: 1
  lifecycle: errand
  vm_type: small
  stemcell: default
  networks: [{name: service-fabric}]
  env:
    bosh:
      ipv6: {enable: true}
  jobs:
  - name: smoke-test
    release: service-fabric

- name: upgrade
  azs: [z1]
  instances: 1
  lifecycle: errand
  vm_type: small
  stemcell: default
  networks: [{name: service-fabric}]
  env:
    bosh:
      ipv6: {enable: true}
  jobs:
  - name: upgrade
    release: service-fabric

variables: []

stemcells:
- alias: default
  os: ubuntu-xenial
  version: 170.9

update:
  canaries: 5
  max_in_flight: 1
  canary_watch_time: 1000-10000
  update_watch_time: 1000-10000
  serial: false

releases:
- name: service-fabric
  sha1: f7d7dfa920678398618d285225fccc1e1e7d9d68
  stemcell:
    os: ubuntu-xenial
    version: "170.9"
  url: https://github.com/starkandwayne/service-fabric-boshrelease/releases/download/v0.7.2/service-fabric-0.7.2.tgz
  version: 0.7.2
